/* eslint-disable react/prop-types */
import { useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { ArrowUp, Bot, ImageIcon, Sparkles, UserRound } from 'lucide-react'
import { assistantClient } from '../lib/assistantClient'
import { parseAssistantIntent } from '../lib/assistantIntent'

const EXAMPLES = ['Show images of left femur', 'Find specimen SK001', 'How do I add a specimen?', 'How do I use the skeleton viewer?']
function ImageCard({ image, onOpen }) { return <button onClick={onOpen} className="grid w-full grid-cols-[88px_1fr] gap-3 rounded-2xl border border-white/10 bg-slate-900/90 p-2 text-left"><div className="flex h-24 items-center justify-center overflow-hidden rounded-xl bg-black/30">{image.imageUrl ? <img src={image.imageUrl} alt={image.boneType || 'Skeletal record'} className="h-full w-full object-cover" /> : <ImageIcon className="h-5 w-5 text-white/30" />}</div><div><p className="font-semibold">{image.boneType || 'Unlabelled bone'}</p><p className="text-xs text-white/45">{[image.skeletonCode, image.side, image.condition].filter(Boolean).join(' · ')}</p><p className="mt-2 text-xs text-white/45">{image.notes || 'No notes recorded.'}</p></div></button> }
function HelpCard({ topic, onNavigate }) { return <div className="mt-4 rounded-2xl border border-emerald-300/20 bg-slate-950/60 p-4"><h3 className="font-semibold text-emerald-100">{topic.title}</h3><p className="mt-2 text-sm text-white/70">{topic.summary}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-white/65">{topic.steps.map((step) => <li key={step}>{step}</li>)}</ol>{topic.importantNotes?.length > 0 && <p className="mt-3 text-xs leading-5 text-emerald-100/75">{topic.importantNotes.join(' ')}</p>}{topic.limitations?.length > 0 && <p className="mt-2 text-xs leading-5 text-amber-100/75">Limitations: {topic.limitations.join(' ')}</p>}{topic.routes?.map((route) => <button key={route.path} onClick={() => onNavigate(route.path)} className="mt-4 rounded-xl border border-emerald-300/30 px-3 py-2 text-xs font-semibold text-emerald-100">{route.label}</button>)}</div> }
function Bubble({ message, navigate }) { const user = message.role === 'user'; return <div className={`flex gap-3 ${user ? 'justify-end' : ''}`}>{!user && <div className="mt-1 flex h-9 w-9 items-center justify-center rounded-full bg-emerald-400/10"><Bot className="h-4 w-4" /></div>}<div className={`max-w-3xl rounded-3xl px-5 py-4 ${user ? 'bg-white text-slate-950' : 'border border-white/10 bg-white/[.04] text-white'}`}><p className="text-sm leading-6">{message.text}</p>{message.type === 'SYSTEM_HELP' && <HelpCard topic={message.topic} onNavigate={navigate} />}{message.type === 'IMAGE_RESULTS' && <div className="mt-4 space-y-2">{message.records.length ? message.records.map((row) => <ImageCard key={row.imageId} image={row} onOpen={() => navigate(`/image/${row.imageId}`)} />) : 'No matching image records found.'}</div>}{message.type === 'SPECIMEN_RESULTS' && <div className="mt-4 space-y-2">{message.records.length ? message.records.map((row) => <button key={row.specimenId} onClick={() => navigate(`/specimens/${row.specimenId}`)} className="block w-full rounded-xl border border-white/10 p-3 text-left text-sm">{row.specimenId} · {[row.skeletonCode, row.boneType, row.side].filter(Boolean).join(' · ')}</button>) : 'No matching specimen records found.'}</div>}{message.type === 'MEASUREMENT_RESULTS' && <div className="mt-4 text-sm text-white/65">{message.records.length ? message.records.map((row) => <p key={row.measurementId}>{[row.boneType, row.measurementType, row.value, row.unit].filter(Boolean).join(' · ')}</p>) : 'No measurements are recorded for this specimen.'}</div>}{message.type === 'COVERAGE_RESULT' && <p className="mt-3 text-xs text-white/55">Recorded category coverage: {message.data.categoryCoveragePercentage}%. Image documentation coverage: {message.data.imageDocumentationPercentage}%. Coverage is OAHRIS documentation, not anatomical completeness.</p>}</div>{user && <UserRound className="mt-2 h-5 w-5" />}</div> }
export default function AIAssistantPage() {
  const navigate = useNavigate(); const location = useLocation(); const [prompt, setPrompt] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState([{ role: 'assistant', text: 'I can retrieve OAHRIS records or explain how to use the current system.' }]); const preview = useMemo(() => parseAssistantIntent(prompt), [prompt])
  const runQuery = async (override) => { const content = (override || prompt).trim(); if (!content || loading) return; const intent = parseAssistantIntent(content); setPrompt(''); setMessages((current) => [...current, { role: 'user', text: content }]); if (intent.type === 'UNSUPPORTED_QUERY') return setMessages((current) => [...current, { role: 'assistant', type: 'UNSUPPORTED_QUERY', text: intent.message }]); setLoading(true); try { let data; if (intent.type === 'SYSTEM_HELP') data = await assistantClient.getSystemHelp(intent.query, location.pathname); else if (intent.type === 'IMAGE_RESULTS') data = await assistantClient.searchImages(intent.filters); else if (intent.type === 'SPECIMEN_RESULTS') data = await assistantClient.searchSpecimens(intent.filters); else if (intent.type === 'MEASUREMENT_RESULTS') data = await assistantClient.getMeasurements(intent.specimenId); else data = await assistantClient.getSkeletonCoverage(intent.skeletonCode); if (data.type === 'HELP_NOT_FOUND') setMessages((current) => [...current, { role: 'assistant', type: 'HELP_NOT_FOUND', text: "I don't have verified OAHRIS guidance for that workflow yet." }]); else { const count = data.records?.length || 0; const text = data.type === 'SYSTEM_HELP' ? data.topic.summary : data.type === 'IMAGE_RESULTS' ? `${count} matching image record${count === 1 ? '' : 's'} found.` : data.type === 'SPECIMEN_RESULTS' ? `${count} matching specimen record${count === 1 ? '' : 's'} found.` : data.type === 'MEASUREMENT_RESULTS' ? `${count} measurement record${count === 1 ? '' : 's'} found.` : `Coverage retrieved for ${data.skeletonCode}.`; setMessages((current) => [...current, { role: 'assistant', type: data.type, text, topic: data.topic, records: data.records || [], data }]) } } catch (error) { setMessages((current) => [...current, { role: 'assistant', type: 'ERROR', text: 'OAHRIS Assistant could not complete the request. Please try again.' }]) } finally { setLoading(false) } }
  return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto flex min-h-[calc(100vh-73px)] max-w-6xl flex-col px-5 py-8"><header className="mb-6"><p className="text-xs uppercase tracking-[.2em] text-emerald-300/70">Read-only retrieval and system guidance</p><h1 className="mt-2 text-3xl font-bold">OAHRIS Assistant</h1><p className="mt-2 text-sm text-white/45">Deterministic record retrieval and practical guidance for current OAHRIS workflows.</p></header><section className="flex-1 space-y-5 rounded-3xl border border-white/10 bg-white/[.03] p-5">{messages.map((message, index) => <Bubble key={index} message={message} navigate={navigate} />)}{loading && <p className="text-sm text-white/50">Retrieving OAHRIS information…</p>}</section><div className="mt-4 rounded-3xl border border-white/10 bg-slate-900 p-3"><div className="mb-3 flex flex-wrap gap-2">{EXAMPLES.map((example) => <button key={example} onClick={() => runQuery(example)} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/60">{example}</button>)}</div><div className="flex gap-3"><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); runQuery() } }} placeholder="Ask about OAHRIS or its workflows…" className="min-h-[48px] flex-1 rounded-2xl border border-white/10 bg-slate-950 p-3 text-sm" /><button onClick={() => runQuery()} className="rounded-2xl bg-white p-3 text-slate-950" aria-label="Send"><ArrowUp /></button></div><p className="mt-2 text-xs text-white/35">{preview.type === 'SYSTEM_HELP' ? 'Recognized system-help request.' : `Recognized request: ${preview.type}`}</p></div></div></main>
}
