/* eslint-disable react/prop-types */
import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { BookOpen, ChevronRight, CircleAlert, ImageIcon, LockKeyhole, MapPin, PanelLeftClose, PanelLeftOpen, Plus, Search, SearchX, Send, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { assistantClient } from '../lib/assistantClient'
import { parseAssistantIntent } from '../lib/assistantIntent'
import { deterministicAssistantMessage, selectAssistantPresentation } from '../lib/assistantPresentation'
import { executeAssistantIntent } from '../lib/assistantRequestRouter'
import SkullyAvatar from '../components/assistant/SkullyAvatar'
import SkullyThinking from '../components/assistant/SkullyThinking'

const QUICK_TASKS = [
  [Search, 'Find a specimen', 'Find specimen SPEC-664'],
  [MapPin, 'Explore a site', 'Find sites from the Anuradhapura period'],
  [ImageIcon, 'View images', 'Show images of left femur'],
  [BookOpen, 'Learn a workflow', 'How do I use the Skeleton Viewer?'],
]
const SUGGESTED_PROMPTS = ['Show images of left femur', 'Find specimen SPEC-664', 'Find sites from the Anuradhapura period', 'Show excavation context for SPEC-664', 'How do I use Spatial Analysis?', 'How do I run Skeletal Analysis?', 'How do I use the Skeleton Viewer?']
const RESPONSE_LABELS = { SYSTEM_HELP: 'System guidance', SITE_RESULTS: 'Site records', SITE_RESULT: 'Site record', SPECIMEN_CONTEXT: 'Stored context', IMAGE_RESULT: 'Image detail', SKELETAL_ANALYSIS_RESULT: 'Stored analysis', DATA_QUALITY_RESULT: 'Data quality' }

function DetailList({ rows }) {
  return <dl className="grid gap-x-5 gap-y-3 sm:grid-cols-2">{rows.filter(([, value]) => value !== undefined && value !== null && value !== '').map(([label, value]) => <div key={label}><dt className="text-[11px] font-medium uppercase tracking-[0.12em] text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-200">{String(value)}</dd></div>)}</dl>
}

function SpecimenCard({ specimen, onOpen }) {
  return <button onClick={onOpen} className="group w-full rounded-xl bg-slate-900/70 px-4 py-3 text-left transition hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-300"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm font-semibold text-teal-100">{specimen.specimenId}</p><p className="mt-1 text-sm text-slate-300">{[specimen.boneType, specimen.side].filter(Boolean).join(' · ') || 'OAHRIS specimen record'}</p></div><ChevronRight className="mt-1 h-4 w-4 text-slate-500 group-hover:text-teal-200" /></div><p className="mt-2 text-xs text-slate-500">{[specimen.skeletonCode, specimen.site, specimen.district].filter(Boolean).join(' · ')}</p></button>
}

function ImageCard({ image, onOpen }) {
  return <button onClick={onOpen} className="group grid w-full grid-cols-[68px_minmax(0,1fr)_auto] items-center gap-3 rounded-xl bg-slate-900/70 p-2.5 text-left transition hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-300"><div className="flex h-14 w-[68px] items-center justify-center overflow-hidden rounded-lg bg-slate-950/80">{image.imageUrl ? <img src={image.imageUrl} alt={image.boneType || 'Skeletal record'} className="h-full w-full object-cover" /> : <ImageIcon className="h-5 w-5 text-slate-600" />}</div><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-100">{image.boneType || 'Skeletal image'}</p><p className="mt-1 truncate text-xs text-slate-400">{[image.skeletonCode || image.specimenId, image.side, image.imageView, image.condition].filter(Boolean).join(' · ')}</p></div><ChevronRight className="h-4 w-4 text-slate-500 group-hover:text-teal-200" /></button>
}

function SiteResultCard({ result, navigate }) {
  if (!result) return null
  if (result.status === 'ambiguous') return <section className="mt-4 rounded-xl bg-amber-300/[0.06] px-4 py-3 text-sm text-amber-100">More than one site shares that name. Use an exact site ID; Skully did not guess.</section>
  if (result.status === 'reference_only') return <section className="mt-4 rounded-xl bg-amber-300/[0.06] p-4"><p className="font-medium text-amber-50">{result.requestedSiteName || 'Referenced site name'}</p><p className="mt-1 text-sm leading-6 text-amber-100/80">This name appears in specimen records, but it does not resolve to a unique stored site record.</p><DetailList rows={[["Linked specimen references", result.linkedSpecimens?.length], ['Site linkage', result.siteLinkageStatus]]} /></section>
  const site = result.site || result
  return <section className="mt-4 rounded-xl bg-slate-950/45 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold text-slate-100">{site.siteName || 'Archaeological site'}</p><p className="mt-1 text-sm text-slate-400">{[site.district, site.province, site.timePeriod].filter(Boolean).join(' · ') || 'Stored OAHRIS site record'}</p></div>{site.siteId && <button onClick={() => navigate(`/parami/site/${encodeURIComponent(site.siteId)}`)} className="shrink-0 text-sm font-medium text-teal-200 transition hover:text-teal-100">Open site</button>}</div><div className="mt-4 border-t border-white/5 pt-4"><DetailList rows={[["Site type", site.siteType], ['Risk level', site.riskLevel], ['Protected status', site.protectedStatus], ['Linked specimens', result.linkedSpecimens?.length]]} /></div></section>
}

function ContextCard({ context }) {
  const site = context.siteResolution || {}; const date = context.laboratoryDating || {}; const excavation = context.excavation || {}
  return <section className="mt-4 overflow-hidden rounded-xl bg-slate-950/45"><div className="flex items-center gap-2 border-b border-white/5 px-4 py-3"><Sparkles className="h-4 w-4 text-teal-300" /><p className="text-sm font-medium text-slate-100">Specimen context · {context.specimen?.specimenId}</p></div><div className="grid divide-y divide-white/5 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="p-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-slate-500">Location</p><p className="mt-2 text-sm font-medium text-slate-200">{site.site?.siteName || context.specimen?.siteName || 'Not recorded'}</p><p className="mt-1 text-xs leading-5 text-slate-400">{[site.site?.district || context.specimen?.district, site.site?.province || context.specimen?.province].filter(Boolean).join(' · ') || 'Site resolution: ' + (site.status || 'not recorded')}</p></div><div className="p-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-slate-500">Dating</p><p className="mt-2 text-sm font-medium text-slate-200">{date.method || 'Not recorded'}</p><p className="mt-1 text-xs leading-5 text-slate-400">{date.result || [date.rangeMinBp, date.rangeMaxBp].filter((value) => value !== null && value !== undefined).join('–') || 'No recorded result'}{date.laboratory ? ` · ${date.laboratory}` : ''}</p></div><div className="p-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-slate-500">Excavation</p><p className="mt-2 text-sm font-medium text-slate-200">{excavation.excavationDate || 'Not recorded'}</p><p className="mt-1 text-xs leading-5 text-slate-400">{excavation.excavationPhase || excavation.notes || 'No additional excavation details recorded'}</p></div></div></section>
}

function ImageDetailCard({ image, navigate }) { if (!image) return null; return <section className="mt-4 rounded-xl bg-slate-950/45 p-4"><div className="flex gap-4">{image.imageUrl && <img src={image.imageUrl} alt={image.boneType || 'OAHRIS image'} className="h-24 w-24 rounded-lg object-cover" />}<div className="min-w-0 flex-1"><p className="font-mono text-sm font-semibold text-teal-100">{image.imageId}</p><p className="mt-1 text-sm text-slate-300">{[image.boneType, image.side, image.imageView].filter(Boolean).join(' · ')}</p><button onClick={() => navigate(`/image/${encodeURIComponent(image.imageId)}`)} className="mt-3 text-sm font-medium text-teal-200">Open image detail</button></div></div><div className="mt-4 border-t border-white/5 pt-4"><DetailList rows={[["Condition", image.condition], ['Image type', image.imageType], ['Specimen', image.specimenId], ['Stored annotations', image.annotations?.length], ['Tags', image.tags?.join(', ')]]} /></div></section> }

function AnalysisResultCard({ analysis, navigate }) { if (!analysis) return null; const predictions = analysis.storedPredictions || {}; return <section className="mt-4 rounded-xl bg-orange-300/[0.045] p-4"><p className="font-medium text-orange-50">Stored Skeletal Analysis Result</p><p className="mt-1 text-xs text-orange-100/65">Produced by the OAHRIS Skeletal Analysis module</p><div className="mt-4"><DetailList rows={[["Case ID", analysis.caseId], ['Sex prediction', predictions.gender || predictions.sex], ['Age range', predictions.ageRange], ['Stature', predictions.height || predictions.stature], ['Confidence', predictions.confidence]]} /></div><button onClick={() => navigate(`/skeletal/report/${encodeURIComponent(analysis.caseId)}`)} className="mt-4 text-sm font-medium text-orange-200">Open stored report</button></section> }

function DataQualityCard({ result }) { if (!result) return null; const check = result.currentCompleteness || {}; return <section className="mt-4 rounded-xl bg-emerald-300/[0.045] p-4"><p className="font-medium text-emerald-50">Data quality · {result.specimenId}</p><div className="mt-4"><DetailList rows={[["Current completeness", `${check.percentage ?? 0}%`], ['Status', check.status], ['Measurements present', check.hasMeasurements ? 'Yes' : 'No'], ['Missing fields', check.missingTrackedFields?.join(', ') || 'None']]} /></div><div className="mt-4 border-t border-emerald-200/10 pt-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-emerald-100/65">Stored Measurement-Analysis Logs</p><p className="mt-2 text-sm text-slate-300">{result.storedMeasurementAnalysisLogs?.length ? `${result.storedMeasurementAnalysisLogs.length} stored log${result.storedMeasurementAnalysisLogs.length === 1 ? '' : 's'} available.` : 'No stored measurement-analysis logs.'}</p></div></section> }

function ResultPresentation({ data, navigate }) { if (!data) return null; return <>{data.helpTopic && <section className="mt-4 rounded-xl bg-teal-300/[0.055] p-4"><p className="font-medium text-teal-50">{data.helpTopic.title}</p><p className="mt-1 text-sm leading-6 text-slate-300">{data.helpTopic.summary}</p></section>}{data.images?.length > 0 && <div className="mt-4 space-y-2">{data.images.map((row) => <ImageCard key={row.imageId} image={row} onOpen={() => navigate(`/image/${row.imageId}`)} />)}</div>}{data.specimens?.length > 0 && <div className="mt-4 space-y-2">{data.specimens.map((row) => <SpecimenCard key={row.specimenId} specimen={row} onOpen={() => navigate(`/specimens/${row.specimenId}`)} />)}</div>}{data.sites?.length > 0 && <div className="mt-4 space-y-2">{data.sites.map((site) => <SiteResultCard key={site.siteId} result={site} navigate={navigate} />)}</div>}{data.site && <SiteResultCard result={data.site} navigate={navigate} />}{data.specimenContext && <ContextCard context={data.specimenContext} />}{data.imageDetail && <ImageDetailCard image={data.imageDetail} navigate={navigate} />}{data.skeletalAnalysis && <AnalysisResultCard analysis={data.skeletalAnalysis} navigate={navigate} />}{data.dataQuality && <DataQualityCard result={data.dataQuality} />}</> }

function AssistantMessage({ message, navigate }) {
  if (message.role === 'user') return <div className="flex justify-end"><div className="max-w-[88%] rounded-2xl rounded-br-md bg-slate-800 px-4 py-3 text-sm leading-6 text-slate-100 shadow-lg shadow-slate-950/20"><p>{message.text}</p></div><UserRound className="ml-3 mt-2 h-5 w-5 shrink-0 text-slate-500" /></div>
  const state = message.type === 'NOT_FOUND' ? [SearchX, 'text-slate-400'] : message.type === 'ACCESS_DENIED' ? [LockKeyhole, 'text-amber-200'] : message.type === 'ERROR' ? [CircleAlert, 'text-rose-200'] : null
  const StateIcon = state?.[0]
  return <div className="flex max-w-4xl items-start gap-3"><SkullyAvatar /><div className="min-w-0 flex-1 pt-1"><div className="mb-1.5 flex items-center gap-2"><p className="text-sm font-semibold text-slate-100">Skully</p>{RESPONSE_LABELS[message.type] && <span className="rounded-full bg-teal-300/[0.08] px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] text-teal-100/80">{RESPONSE_LABELS[message.type]}</span>}</div><div className={StateIcon ? 'flex gap-2 text-sm leading-6 text-slate-300' : 'text-sm leading-6 text-slate-300'}>{StateIcon && <StateIcon className={`mt-1 h-4 w-4 shrink-0 ${state[1]}`} />}<p>{message.text}</p></div><ResultPresentation data={selectAssistantPresentation(message)} navigate={navigate} /></div></div>
}

function AssistantSidebar({ collapsed, onCollapse, onNewChat, onPrompt, loading }) {
  return <aside className={`hidden shrink-0 border-r border-white/5 bg-slate-950/50 transition-[width] duration-200 lg:flex lg:flex-col ${collapsed ? 'w-[76px]' : 'w-[280px]'}`} aria-label="Skully assistant tools"><div className="flex items-center gap-2 p-3">{!collapsed && <button onClick={onNewChat} disabled={loading} className="flex h-11 flex-1 items-center gap-2 rounded-xl bg-teal-300/[0.1] px-3 text-sm font-medium text-teal-50 transition hover:bg-teal-300/[0.16] disabled:opacity-50"><Plus className="h-4 w-4" />New chat</button>}<button onClick={collapsed ? onNewChat : onCollapse} disabled={loading} className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-slate-400 transition hover:bg-white/5 hover:text-teal-100 disabled:opacity-50" aria-label={collapsed ? 'Start new chat' : 'Collapse assistant sidebar'} title={collapsed ? 'New chat' : 'Collapse sidebar'}>{collapsed ? <Plus className="h-5 w-5" /> : <PanelLeftClose className="h-5 w-5" />}</button></div>{collapsed ? <div className="flex flex-1 flex-col items-center gap-3 pt-2">{QUICK_TASKS.map(([Icon, label, prompt]) => <button key={label} onClick={() => onPrompt(prompt)} disabled={loading} title={label} aria-label={label} className="inline-flex h-10 w-10 items-center justify-center rounded-lg text-slate-400 transition hover:bg-teal-300/[0.09] hover:text-teal-200"><Icon className="h-4 w-4" /></button>)}<button onClick={onCollapse} className="mt-auto mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg text-slate-500 transition hover:bg-white/5 hover:text-slate-200" aria-label="Expand assistant sidebar"><PanelLeftOpen className="h-5 w-5" /></button></div> : <div className="flex-1 overflow-y-auto px-3 pb-5"><SidebarHeading>Quick tasks</SidebarHeading><div className="grid grid-cols-2 gap-2">{QUICK_TASKS.map(([Icon, label, prompt]) => <button key={label} onClick={() => onPrompt(prompt)} disabled={loading} className="flex min-h-[74px] flex-col items-start gap-2 rounded-xl bg-slate-900/65 p-3 text-left text-xs text-slate-300 transition hover:bg-slate-800 hover:text-teal-50 disabled:opacity-50"><Icon className="h-4 w-4 text-teal-300" />{label}</button>)}</div><SidebarHeading>Suggested prompts</SidebarHeading><div className="space-y-1">{SUGGESTED_PROMPTS.map((prompt) => <button key={prompt} onClick={() => onPrompt(prompt)} disabled={loading} className="flex w-full items-start gap-2 rounded-lg px-2 py-2 text-left text-sm leading-5 text-slate-400 transition hover:bg-white/[0.035] hover:text-slate-100 disabled:opacity-50"><Sparkles className="mt-1 h-3 w-3 shrink-0 text-teal-300" /><span>{prompt}</span></button>)}</div></div>}</aside>
}
function SidebarHeading({ children }) { return <p className="mb-3 mt-6 text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500">{children}</p> }

function EmptyState({ onPrompt, loading }) { return <div className="mx-auto flex w-full max-w-4xl flex-col items-center px-4 py-10 text-center sm:py-16"><SkullyAvatar size="large" /><div className="mt-5"><div className="flex items-center justify-center gap-2"><h1 className="text-3xl font-semibold tracking-tight text-white">Skully</h1><span className="rounded-full bg-teal-300/[0.1] px-2.5 py-1 text-xs font-medium text-teal-100">OAHRIS Model 1.1</span></div><p className="mt-3 text-xl text-slate-200 sm:text-2xl">What can I help you explore in OAHRIS?</p></div><div className="mt-7 grid w-full gap-3 sm:grid-cols-2 lg:grid-cols-4">{QUICK_TASKS.map(([Icon, label, prompt]) => <button key={label} onClick={() => onPrompt(prompt)} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900/65 px-4 py-4 text-sm font-medium text-slate-200 transition hover:bg-slate-800 hover:text-teal-50 disabled:opacity-50"><Icon className="h-5 w-5 text-teal-300" />{label}</button>)}</div></div> }

function Composer({ prompt, setPrompt, runQuery, loading }) { return <div className="border-t border-white/5 bg-slate-950/75 px-4 pb-4 pt-3 backdrop-blur sm:px-6"><div className="rounded-2xl bg-slate-900/85 p-3 shadow-[0_0_0_1px_rgba(45,212,191,0.12),0_12px_30px_rgba(2,6,23,0.35)] transition focus-within:shadow-[0_0_0_1px_rgba(45,212,191,0.55),0_0_28px_rgba(20,184,166,0.12)]"><textarea value={prompt} maxLength={1000} disabled={loading} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); runQuery() } }} placeholder="Ask Skully about OAHRIS records, workflows, or system guidance..." className="min-h-[62px] max-h-36 w-full resize-y bg-transparent px-2 py-1 text-sm leading-6 text-slate-100 outline-none placeholder:text-slate-500 disabled:cursor-not-allowed" /><div className="mt-2 flex items-center justify-between gap-3 px-1"><div className="flex items-center gap-2"><span className="rounded-lg bg-teal-300/[0.1] px-2.5 py-1 text-xs font-medium text-teal-100">OAHRIS Model 1.1</span><span className="rounded-lg bg-white/[0.045] px-2.5 py-1 text-xs text-slate-300">Fast</span><span className="hidden text-xs text-slate-500 sm:inline">{prompt.length}/1000</span></div><button disabled={loading || !prompt.trim()} onClick={() => runQuery()} className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-teal-300 text-slate-950 transition hover:bg-teal-200 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-500" aria-label="Send message">{loading ? <span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-700 border-t-transparent motion-reduce:animate-none" /> : <Send className="h-4 w-4" />}</button></div></div><p className="mt-2 text-center text-xs text-slate-600">Skully can make mistakes. Verify important information from OAHRIS records.</p></div> }

export default function AIAssistantPage() {
  const navigate = useNavigate(); const location = useLocation(); const endRef = useRef(null)
  const [prompt, setPrompt] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState([]); const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: loading ? 'auto' : 'smooth', block: 'end' }) }, [messages, loading])
  const runQuery = async (override) => {
    const content = (override || prompt).trim(); if (!content || loading) return
    const intent = parseAssistantIntent(content); const previousUserMessage = [...messages].reverse().find((message) => message.role === 'user')?.text; const previousAssistantMessage = [...messages].reverse().find((message) => message.role === 'assistant')?.text
    const context = previousUserMessage ? { previousUserMessage: previousUserMessage.slice(0, 500), ...(previousAssistantMessage ? { previousAssistantMessage: previousAssistantMessage.slice(0, 700) } : {}) } : undefined
    setPrompt(''); setMessages((current) => [...current, { role: 'user', text: content }]); setLoading(true)
    try { const data = await executeAssistantIntent(intent, { content, currentRoute: location.pathname, context }, assistantClient); const nextMessage = intent.type === 'UNSUPPORTED_QUERY' ? { role: 'assistant', type: data.type, text: data.answer, presentation: data.presentation, sources: data.sources, meta: data.meta } : deterministicAssistantMessage(data); setMessages((current) => [...current, nextMessage]) } catch (error) { const restricted = error?.code === 'ACCESS_DENIED'; const sessionExpired = error?.code === 'AUTH_REQUIRED' || error?.code === 'AUTH_SESSION_INVALID'; const text = restricted || sessionExpired ? error.message : "Skully couldn't complete that request. Please try again."; setMessages((current) => [...current, { role: 'assistant', type: restricted ? 'ACCESS_DENIED' : 'ERROR', text }]) } finally { setLoading(false) }
  }
  const newChat = () => { if (!loading) { setPrompt(''); setMessages([]) } }
  return <main className="min-h-[calc(100vh-120px)] bg-slate-950 text-white"><div className="flex min-h-[calc(100vh-120px)]"><AssistantSidebar collapsed={sidebarCollapsed} onCollapse={() => setSidebarCollapsed((value) => !value)} onNewChat={newChat} onPrompt={runQuery} loading={loading} /><section className="flex min-w-0 flex-1 flex-col"><header className="flex items-center justify-between gap-3 border-b border-white/5 px-4 py-3 sm:px-6"><button onClick={() => setSidebarCollapsed((value) => !value)} className="hidden h-9 w-9 items-center justify-center rounded-lg text-slate-500 transition hover:bg-white/5 hover:text-slate-200 lg:inline-flex" aria-label={sidebarCollapsed ? 'Expand assistant sidebar' : 'Collapse assistant sidebar'}>{sidebarCollapsed ? <PanelLeftOpen className="h-4 w-4" /> : <PanelLeftClose className="h-4 w-4" />}</button><div className="flex items-center gap-2"><SkullyAvatar size="medium" /><p className="font-semibold text-slate-100">Skully</p><span className="hidden rounded-full bg-teal-300/[0.08] px-2 py-0.5 text-xs text-teal-100 sm:inline">OAHRIS Model 1.1</span></div><div className="flex items-center gap-2 rounded-lg bg-teal-300/[0.055] px-3 py-2 text-xs text-teal-100" title="Skully can retrieve information and provide guidance but cannot modify OAHRIS records."><ShieldCheck className="h-4 w-4" /><span className="hidden sm:inline">Read-only assistant</span></div></header><div className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto flex min-h-full w-full max-w-6xl flex-col px-4 sm:px-6">{messages.length === 0 ? <EmptyState onPrompt={runQuery} loading={loading} /> : <div className="py-7"><div className="mb-7 flex items-center justify-between gap-4"><div><h1 className="text-xl font-semibold text-white">Skully</h1><p className="mt-1 text-sm text-slate-400">OAHRIS records, workflows, and system guidance.</p></div><span className="rounded-full bg-white/[0.045] px-2.5 py-1 text-xs text-slate-400">Fast</span></div><div className="space-y-6">{messages.map((message, index) => <AssistantMessage key={index} message={message} navigate={navigate} />)}{loading && <SkullyThinking />}</div></div>}{messages.length === 0 && loading && <div className="pb-5"><SkullyThinking /></div>}<div ref={endRef} /></div></div><Composer prompt={prompt} setPrompt={setPrompt} runQuery={runQuery} loading={loading} /></section></div></main>
}
